name: Deploy Backend Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Kode Backend
        uses: actions/checkout@v3

      - name: Deploy ke VM Backend via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.BACKEND_SSH_HOST }}
          username: ${{ secrets.BACKEND_SSH_USER }}
          key: ${{ secrets.BACKEND_SSH_KEY }}
          port: 22
          script: |
            echo "Masuk ke VM Backend"
            cd /home/pbluser/backend-genzett
            git pull origin main
            docker compose down
            docker compose up -d --build
